name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: pacman
          cx_tenant: tylertech
          base_uri: https://ast.checkmarx.net
          additional_params: --project-groups 'Public Safety' --apikey ${{ secrets.CX_API_KEY}} 
