name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: pacman
          cx_tenant: tylertech
          base_uri: https://ast.checkmarx.net
          additional_params: --project-groups Public Safety --apikey eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMDBkMjY0ZS05NGJmLTQ5OTAtYWVkYy0yMGRhODIzNDAzNTYifQ.eyJpYXQiOjE2NjE5NjE0NTgsImp0aSI6IjEwMTQzMWMwLTBlNTMtNDM1NS1hYmU5LTA4YTc1ZmY1MDU3NCIsImlzcyI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvdHlsZXJ0ZWNoIiwiYXVkIjoiaHR0cHM6Ly9pYW0uY2hlY2ttYXJ4Lm5ldC9hdXRoL3JlYWxtcy90eWxlcnRlY2giLCJzdWIiOiJiMTJkMDE5MC03YzM3LTQzOWItYWYzYy1jZWQzYzkyOTU4MjMiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoiYXN0LWFwcCIsInNlc3Npb25fc3RhdGUiOiJmNjFmZGRiYi02ZGY0LTRjYzctYTRjNi00NDNhOTk2MDdhODYiLCJzY29wZSI6IiBvZmZsaW5lX2FjY2VzcyIsInNpZCI6ImY2MWZkZGJiLTZkZjQtNGNjNy1hNGM2LTQ0M2E5OTYwN2E4NiJ9.vTKMIvos9umlQ28JWbpVh3P8Dc9dF5ljrOCImupXeJs
