name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: antivirus
          cx_tenant: tylertech
          base_uri: https://ast.checkmarx.net
          cx_APIKEY: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMDBkMjY0ZS05NGJmLTQ5OTAtYWVkYy0yMGRhODIzNDAzNTYifQ.eyJpYXQiOjE2NjE5NDY1OTMsImp0aSI6IjhkZjU2MGMxLTc5Y2UtNDIxMC04ODk5LTU5MzFmNGYyN2ZiNCIsImlzcyI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvdHlsZXJ0ZWNoIiwiYXVkIjoiaHR0cHM6Ly9pYW0uY2hlY2ttYXJ4Lm5ldC9hdXRoL3JlYWxtcy90eWxlcnRlY2giLCJzdWIiOiJiMTJkMDE5MC03YzM3LTQzOWItYWYzYy1jZWQzYzkyOTU4MjMiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoiYXN0LWFwcCIsInNlc3Npb25fc3RhdGUiOiJiM2M2MWExYS0wMWFjLTRiYmQtOGZhMC0yN2ExYTU2YThiZDMiLCJzY29wZSI6IiBvZmZsaW5lX2FjY2VzcyIsInNpZCI6ImIzYzYxYTFhLTAxYWMtNGJiZC04ZmEwLTI3YTFhNTZhOGJkMyJ9.RG2Z5H7V7jZHzBx1bBcgQk1brq1iHD7NABBqJCvOIOk
         
